version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    command: nginx -g 'daemon off;'
    networks:
      - monitoring
    restart: always
  prometheus:
    image: prometheus/prometheus:latest
    container_name: prometheus
    volumes:
      - /mnt/config
      - /var/log:/var/log
      - ./promtail-config.yaml:/mnt/config/promtail-config.yaml
    command: -config.file=/mnt/config/promtail-config.yaml
    networks:
      - monitoring
    restart: always
  
  grafana:
    image: grafana/grafana:8.0.6
    ports:
      - "3000:3000"
    networks:
      - monitoring
    restart: always
  
networks:
  monitoring:
      driver: bridge